services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  localstack:
      image: localstack/localstack
      environment:
        - SERVICES=s3
        - AWS_DEFAULT_REGION=us-east-1
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
      ports:
        - "4566:4566"  # Основной порт для LocalStack
      volumes:
        - "./localstack:/var/lib/localstack"
volumes:
    app:
    db:
    localstack:


