services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  db: