services:
  # app:
  #   restart: always
  #   image: candles
  #   container_name: golang-app
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - localstack
  #   environment:
  #     - TELEGRAM_BOT_TOKEN=7508240683:AAHAUrhIH9zTe_ogqEYA9HT8oUUDvLoAUps
  #     - JWT_SECRET=sdw@#!@#Fxd
  #     - CONFIG_PATH=./config/config.yaml
  #     - STORAGE_PATH=postgresql://postgres:postgres@localhost:5432/postgres?ssl=disabled
  #     - PASSWORD_POSTGRES=postgres
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  localstack:
    restart: always
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"  # Основной порт для LocalStack
    volumes:
      - "./localstack:/var/lib/localstack"
volumes:
  # db:
  localstack:
  app:
