package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"github.com/Sanchir01/candles_backend/internal/feature/user"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
	customMiddleware "github.com/Sanchir01/candles_backend/internal/handlers/middleware"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"
)

// Login is the resolver for the login field.
func (r *authMutationsResolver) Login(ctx context.Context, obj *model.AuthMutations, input model.LoginInput) (model.LoginResult, error) {
	usersdb, err := r.authStr.Login(ctx, input.Phone)
	if err != nil {
		r.env.Logger.Error("login errors", err.Error())
		return nil, err
	}
	w := customMiddleware.GetResponseWriter(ctx)
	if err = user.AddCookieTokens(usersdb.ID, usersdb.Role, w); err != nil {
		r.env.Logger.Error("error creating cookie jwt", err.Error())
		return responseErr.NewInternalErrorProblem("Error for generating jwt tokens"), nil
	}

	return model.LoginOk{ID: usersdb.ID, Phone: usersdb.Phone, VerifyCode: "sdaddw21", Role: usersdb.Role}, nil
}
