package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/Sanchir01/candles_backend/internal/feature/user"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
	customMiddleware "github.com/Sanchir01/candles_backend/internal/handlers/middleware"
)

// DeleteToken is the resolver for the deleteToken field.
func (r *authMutationsResolver) DeleteToken(ctx context.Context, obj *model.AuthMutations) (model.DeleteTokensResult, error) {
	w := customMiddleware.GetResponseWriter(ctx)
	user.DeleteCookie(w)

	return model.DeleteTokensOk{
		Ok: "success",
	}, nil
}
