package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	runtime "github.com/Sanchir01/candles_backend/internal/gql/generated"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// Auth is the resolver for the auth field.
func (r *mutationResolver) Auth(ctx context.Context) (*model.AuthMutations, error) {
	return &model.AuthMutations{}, nil
}

// AuthMutations returns runtime.AuthMutationsResolver implementation.
func (r *Resolver) AuthMutations() runtime.AuthMutationsResolver { return &authMutationsResolver{r} }

type authMutationsResolver struct{ *Resolver }
