package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.51

import (
	"context"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// Login is the resolver for the login field.
func (r *authMutationsResolver) Login(ctx context.Context, obj *model.AuthMutations, input model.LoginInput) (model.LoginResult, error) {

	user, err := r.authStr.Login(ctx, input.Phone)
	if err != nil {
		r.lg.Error("login errors", err)
		return nil, err
	}
	r.lg.Warn("login", user)
	return model.LoginOk{ID: user.ID, Phone: user.Phone, VerifyCode: "sdaddw21", Role: user.Role}, nil
}
