package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// CandleBySlug is the resolver for the candleBySlug field.
func (r *candlesQueryResolver) CandleBySlug(ctx context.Context, obj *model.CandlesQuery, input model.CandlesBySlugInput) (model.CandlesBySlugResult, error) {
	candles, err := r.env.Services.CandlesService.CandlesBySlug(ctx, input.Slug)
	if err != nil {
		return nil, err
	}
	return model.CandlesBySlugOk{Candle: candles}, nil
}
