package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// CreateCandle is the resolver for the createCandle field.
func (r *candlesMutationResolver) CreateCandle(ctx context.Context, obj *model.CandlesMutation, input model.CreateCandleInput) (model.CandlesMutationResult, error) {
	panic(fmt.Errorf("not implemented: CreateCandle - createCandle"))
}
