package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"
	"github.com/Sanchir01/candles_backend/pkg/lib/utils"
	_ "github.com/lib/pq"
)

// CreateCandle is the resolver for the createCandle field.
func (r *candlesMutationResolver) CreateCandle(ctx context.Context, obj *model.CandlesMutation, input model.CreateCandleInput) (model.CandlesMutationResult, error) {
	slug, err := utils.Slugify(input.Title)
	if err != nil {
		return responseErr.NewInternalErrorProblem("не удалось создат слаг"), err
	}
	_, err = r.candlesStr.CandlesById(ctx, input.CategoryID)
	if err == nil {
		return responseErr.NewInternalErrorProblem("товар с таким айди уже е сть"), err
	}

	_, err = r.candlesStr.CandlesBySlug(ctx, slug)
	if err == nil {
		return responseErr.NewInternalErrorProblem("такая категория уже есть"), err
	}

	id, err := r.candlesStr.CreateCandles(ctx, input.CategoryID, input.Title, slug, input.Images)
	if err != nil {
		return responseErr.NewInternalErrorProblem("ошибка во время создания свечи"), err
	}
	return &model.CandlesCreateOk{
		ID: id,
	}, nil
}
