package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	runtime "github.com/Sanchir01/candles_backend/internal/gql/generated"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// Candles is the resolver for the candles field.
func (r *queryResolver) Candles(ctx context.Context) (*model.CandlesQuery, error) {
	return &model.CandlesQuery{}, nil
}

// CandlesQuery returns runtime.CandlesQueryResolver implementation.
func (r *Resolver) CandlesQuery() runtime.CandlesQueryResolver { return &candlesQueryResolver{r} }

type candlesQueryResolver struct{ *Resolver }
