package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// Delete is the resolver for the delete field.
func (r *categoryMutationResolver) Delete(ctx context.Context, obj *model.CategoryMutation, input *model.DeleteCategoryInput) (model.DeleteCategoryResult, error) {
	panic(fmt.Errorf("not implemented: Delete - delete"))
}
