package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"
)

// CategoryBySlug is the resolver for the categoryBySlug field.
func (r *categoryQueryResolver) CategoryBySlug(ctx context.Context, obj *model.CategoryQuery, input model.CategoryBySlugInput) (model.CategoryBySlugResult, error) {
	category, err := r.env.Repositories.CategoryRepository.CategoryBySlug(ctx, input.Slug)
	if err != nil {
		return responseErr.NewInternalErrorProblem("не удалось получить категорию"), err
	}
	return model.CategoryBySlugOk{Category: category}, nil
}
