package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"
)

// CategoryByID is the resolver for the categoryById field.
func (r *categoryQueryResolver) CategoryByID(ctx context.Context, obj *model.CategoryQuery, input model.CategoryByIDInput) (model.CategoryByIDResult, error) {
	category, err := r.env.Services.CategoryService.CategoryById(ctx, input.ID)

	if err != nil {
		return responseErr.NewInternalErrorProblem("не удалось получить категорию"), err
	}
	return model.CategoryByIDOk{Category: category}, nil
}
