package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// UpdateColor is the resolver for the updateColor field.
func (r *colorMutationResolver) UpdateColor(ctx context.Context, obj *model.ColorMutation, input model.UpdateColorInput) (model.UpdateColorResult, error) {
	panic(fmt.Errorf("not implemented: UpdateColor - updateColor"))
}
