package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// CategoryByManyIds is the resolver for the categoryByManyIds field.
func (r *colorQueryResolver) CategoryByManyIds(ctx context.Context, obj *model.ColorQuery, input model.ColorByIdsInput) (model.ColorByIdsResult, error) {

	return model.ColorByIdsOk{Colors: nil}, nil
}
