package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// CreateColor is the resolver for the createColor field.
func (r *colorMutationResolver) CreateColor(ctx context.Context, obj *model.ColorMutation, input model.CreateColorInput) (model.ColorCreateResult, error) {
	id, err := r.env.Services.ColorService.CreateColor(ctx, input.Title)
	if err != nil {
		return responseErr.NewInternalErrorProblem("error for create color"), err
	}
	return model.ColorCreateOk{ID: id}, nil
}
