package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"
)

// AllColor is the resolver for the allColor field.
func (r *colorQueryResolver) AllColor(ctx context.Context, obj *model.ColorQuery) (model.AllColorResult, error) {
	colors, err := r.env.Services.ColorService.AllColor(ctx)

	if err != nil {
		return responseErr.NewInternalErrorProblem("error for mapping gql model"), err
	}
	return model.AllColorOk{Colors: colors}, nil
}
