package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// CategoryByManyID is the resolver for the categoryByManyId field.
func (r *colorQueryResolver) CategoryByManyID(ctx context.Context, obj *model.ColorQuery, input model.ColorByIDInput) (model.ColorByIDResult, error) {
	panic(fmt.Errorf("not implemented: CategoryByManyID - categoryByManyId"))
}
