package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/Sanchir01/candles_backend/internal/gql/model"
	responseErr "github.com/Sanchir01/candles_backend/pkg/lib/api/response"
)

// Delete is the resolver for the delete field.
func (r *colorMutationResolver) Delete(ctx context.Context, obj *model.ColorMutation, input *model.DeleteColorInput) (model.DeleteColorResult, error) {
	id, err := r.env.Services.ColorService.DeleteColorById(
		ctx, input.ID)

	if err != nil {
		return responseErr.NewInternalErrorProblem("error for delete color"), err
	}
	return model.DeleteColorOk{
		Ok: id,
	}, nil
}
