package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	runtime "github.com/Sanchir01/candles_backend/internal/gql/generated"
	"github.com/Sanchir01/candles_backend/internal/gql/model"
)

// Orders is the resolver for the orders field.
func (r *mutationResolver) Orders(ctx context.Context) (*model.OrderMutations, error) {
	return &model.OrderMutations{}, nil
}

// OrderMutations returns runtime.OrderMutationsResolver implementation.
func (r *Resolver) OrderMutations() runtime.OrderMutationsResolver { return &orderMutationsResolver{r} }

type orderMutationsResolver struct{ *Resolver }
