env: "development"

database:
  host: "localhost"
  port: "5435"
  user: "postgres"
  ssl: "disable"
  dbname: "test"
  max_attempts: 10

s3store:
  key: "44YEJC1KE8L28V73VF43" 
  url: "https://s3.timeweb.cloud"
  region: "ru-1"

gql_server:
    port: "5000"
    host: "localhost"
    timeout: 5s
    debug: true
    idle_timeout: 60s
    max_attempts: 10

errors:
  bad_request:
    message: "не правильный запрос"
    code: 400
  unauthorized:
    message: "unauthorized"
    code: 401
  not_found:
    message: "не правильно введены данные"
    code: 404
  not_implemented:
    message: "not implemented"
    code: 500


