env: "development"

database:
  host: localhost
  port: "5432"
  user: "postgres"
  dbname: "test"
  max_attempts: 10

domain: "localhost"

prometheus:
  host: "localhost"
  port: 8081
  timeout: 4s
  debug: true
  idle_timeout: 60s

http_server:
  host: 0.0.0.0
  port: 5000
  timeout: 4s
  debug: true
  idle_timeout: 60s

grpc:
  port: 7000
  timeout: 360

s3store:
  url: "https://s3.timeweb.cloud"
  region: "ru-1"
  bucketname: "14e29e5b-46a00c68-6e30-4d39-ae5e-35075eefe000"

gql_server:
  port: "5000"
  host: 0.0.0.0
  timeout: 5s
  debug: true
  idle_timeout: 60s
  max_attempts: 10

errors:
  bad_request:
    message: "не правильный запрос"
    code: 400
  unauthorized:
    message: "unauthorized"
    code: 401
  not_found:
    message: "не правильно введены данные"
    code: 404
  not_implemented:
    message: "not implemented"
    code: 500
