env: "production"

database:
  host: 103.74.92.37
  port: "5432"
  user: "postgres"
  dbname: "postgres"
  max_attempts: 10

kafka:
  producer:
    topic: "order"
    brokers:
      - "103.74.92.37:9092"
redis:
  host: 103.74.92.37
  port: "5433"
  retries: 5
  dbnumber: 0

domain: "localhost"

prometheus:
  host: 0.0.0.0
  port: 4001
  timeout: 4s
  debug: true
  idle_timeout: 60s

http_server:
  host: 0.0.0.0
  port: 5000
  timeout: 4s
  debug: true
  idle_timeout: 60s

grpc:
  port: 7000
  timeout: 360

s3store:
  url: "https://s3.timeweb.cloud"
  region: "ru-1"
  bucketname: "14e29e5b-46a00c68-6e30-4d39-ae5e-35075eefe000"

errors:
  bad_request:
    message: "не правильный запрос"
    code: 400
  unauthorized:
    message: "unauthorized"
    code: 401
  not_found:
    message: "не правильно введены данные"
    code: 404
  not_implemented:
    message: "not implemented"
    code: 500
