global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "mahakala"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["app:8081"]
