name: Deploy App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.tag}}
      - name: Check if tag exists
        run: |
            git fetch --all --tags
            if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
              echo "error: Tag '${{ github.event.inputs.tag }}' not found"
              exit 1
            fi
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Build app
        run: |
            go mod download
            go build -o ./.bin/main ./cmd/main/main.go


